### ISSUE TITLE
Mongolian Beef recipe

### ISSUE THREAD

**Issue by teleject** [clarklab/chowdown#1]
So... basic question: What step does the beef get cooked? Asking for friend.

**Comment by clarklab** [comment]
This was that recipe I added the other night as I was cooking it, haha. Beef steps coming soon (what's currently listed was just for the sauce). The recipe I started with called for frying the beef, I didn't want to do that.

**Comment by clarklab** [comment]
Only a few **checks calendar** YEARS late, but this is sorted!
