### ISSUE TITLE
Website not displaying correctly.

### ISSUE THREAD

**Issue by muygalan** [clarklab/chowdown#11]
Hi Clark!

For some reason the website is not displaying correctly when I push it into [my own repo](https://github.com/muygalan/recipes).

Current Website: [My Online Recipes](http://www.joshuagalan.com/recipes/)

Steps:
1. I created my own repo on Github called "recipes"
2. I cloned your repo locally. 
3. I deleted your CNAME file.
4. I then changed the remote url from your repo url to my "recipes" url.
5. I added, committed, and push the files to my repo.

Oddly enough, when I run `jekyll serve` locally, the website looks normal. –Any thoughts?

**Comment by di-dc** [comment]
It looks like the /recipes/ path on your site messes up the paths for the CSS/images/etc, leading to a lot of 404s.

Did you update _config.yml? I'm not positive, but I _think_ you need to set:
baseurl: "http://www.joshuagalan.com/recipes/"

**Comment by clarklab** [comment]
I think @di-dc has the right answer.

I'll admit I'm still learning how Jekyll handles URLs, which is one reason I left "baseurl" setting empty. Locally and online I run it in a root folder. If you're in a directory, you'll probably need to update that setting.

**Comment by muygalan** [comment]
@di-dc Your recommendation worked like a charm. Thanks for the help everyone. 👍
