### ISSUE TITLE
Search showing no results

### ISSUE THREAD

**Issue by carlyman** [clarklab/chowdown#13]
Is there anything else needed to get search functionality to work beyond what's in the repo and config defaults?  After getting my recipes in, building, and then serving via localhost...the search field returns nothing (including on the beta page).

**Comment by clarklab** [comment]
Dang! There shouldn't be any extra setup, that I can recall, but to figure it out, let's start with a few simple bits:

- does search work for you on the hosted https://chowdown.io/search site?
- is your local install inside a sub folder? (we've found a few issues with running in a folder, been solving them with baseurl fixes)

**Comment by di-dc** [comment]
@clarklab I think you may be onto the issue -- looks like the search js and json paths don't work when using a subfolder (eg. when baseurl isn't empty).

I just submitted a pull request that I think should correct the issue (or at least, does for me locally): https://github.com/clarklab/chowdown/pull/14

**Comment by carlyman** [comment]
Pulled the latest, but looks like my problem was a different one.  While my recipes showed up fine when browsing, I had some single double-quotes that seemed to cause the issue (e.g. cut into 1" strips).  No easy way to escape them or bulk edit them from what I can tell.

**Comment by di-dc** [comment]
@carlyman I just submitted a new pull request that should correct the issue. Looks like they can be escaped during the process that the search index gets built, based on this:
https://github.com/christian-fei/Simple-Jekyll-Search/wiki#if-search-isnt-working-due-to-invalid-json

I did a test run locally and via github pages, and it seems to fix it.

**Comment by carlyman** [comment]
Awesome!  Just saw the pull request.  Assume this covers with directions and ingredients (and components)?

**Comment by carlyman** [comment]
Merged the changes locally, and search works...thanks!

**Comment by di-dc** [comment]
Glad it worked! 
For reference, right now only Title, Ingredients, Image, and URL are indexed; directions are not.

**Comment by clarklab** [comment]
Great catch! Just merged your PR
