### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Skn0tt** [clarklab/chowdown#17]
I am thinking about creating a fork of *chowdown* that is based on [Gatsby](https://www.gatsbyjs.org/).
If that's OK with you, I'd be happy if you could add an open-source license to *chowdown* so that is legally alright.

**Comment by clarklab** [comment]
Done! Chowdown is completely free and open-source, I've added a license file to the repo to reflect that.

Please keep me posted, I'd love to hear more about a Gatsby fork.

**Comment by Skn0tt** [comment]
Thank you very much!
The fork is available at https://github.com/Skn0tt/chowdown.
It does not aim to deliver feature parity with clarklab/chowdown as it was created primarily for learning about Gatsby.
I will create my own small cookbook using it.
If you want, I can post a link once it is available so you can see the Gatsby fork in action.
