### ISSUE TITLE
Change blue to "food" color?

### ISSUE THREAD

**Issue by teleject** [clarklab/chowdown#2]
Would you be open to changing the blue color to one more suitable for food? Maybe #CC0000? Red, I've found, is commonly found in fast food and restaurants.

> While blue is one of the most popular colors it is one of the least appetizing. Blue food is rare in nature. Food researchers say that when humans searched for food, they learned to avoid toxic or spoiled objects, which were often blue, black, or purple. When food dyed blue is served to study subjects, they lose appetite.
> 
> Green, brown, and red are the most popular food colors. Red is often used in restaurant decorating schemes because it is an appetite stimulant.

[http://www.infoplease.com/spot/colors1.html](http://www.infoplease.com/spot/colors1.html)

![fullscreen_6_27_15__8_38_pm](https://cloud.githubusercontent.com/assets/41737/8394733/82b8a2bc-1d0c-11e5-8c32-647aa9bc8fb1.jpg)

**Comment by rbuzzell** [comment]
I'm a fan of the green #2ecc40, it is a better food color than blue, and isn't quite as jarring as the red. It's still really bright though.

<img width="759" alt="screen shot 2016-11-07 at 1 08 56 pm" src="https://cloud.githubusercontent.com/assets/2417192/20069648/66b4d668-a4eb-11e6-8275-10e6bc52a92f.png">

I'm a fan of olive #3d9970, it stays in the green family but is a bit more muted.
<img width="1160" alt="screen shot 2016-11-07 at 1 13 52 pm" src="https://cloud.githubusercontent.com/assets/2417192/20069812/1103b7d8-a4ec-11e6-8ec2-2300f8b7844d.png">

Or a silver #dddd, it's also less jarring and a more neutral tone.
<img width="699" alt="screen shot 2016-11-07 at 1 11 02 pm" src="https://cloud.githubusercontent.com/assets/2417192/20069831/278fc348-a4ec-11e6-87f5-59215b0aaaa6.png">

**Comment by clarklab** [comment]
I'm quite a big fan of the blue logo/branding, but I do agree we could change the hover color. Maybe just get rid of the color all together and just use a tiny dip in image opacity?

**Comment by clarklab** [comment]
Closing for now, as the design is about to be heavily in flux.
