### ISSUE TITLE
Superseded attributes for Recipe 

### ISSUE THREAD

**Issue by deveth0** [clarklab/chowdown#3]
Hi Clark ,

thanks for your awesome work, really appreciate that you opensourced it! I think I found some minor flaws in the itemdrop properties you are using.
Having a look a http://schema.org/Recipe it seems as if those are superseded by more specific attributes.

| used | by spec |
|---|---|
| ingredient  |  recipeIngredient |
| instructions | recipeInstructions | 

Cheers

**Comment by clarklab** [comment]
A bit late, but these are in place!
