### ISSUE TITLE
Link to example md returns 404

### ISSUE THREAD

**Issue by mysticaltech** [clarklab/chowdown#5]
Hey man, clicking on https://raw.githubusercontent.com/clarklab/chowdown/gh-pages/_recipes/broccoli-cheese-soup.md returns a 404

**Comment by ssteinerx** [comment]
And still does on October 30, 2017.

**Comment by dylan-k** [comment]
The link might be broken still, but you can see the recipes in the _recipes folder of the master branch, for example at https://github.com/clarklab/chowdown/tree/master/_recipes

**Comment by clarklab** [comment]
Fixed!
