### ISSUE TITLE
Beta: Search breaks layout

### ISSUE THREAD

**Issue by aberres** [clarklab/chowdown#9]
In the new beta design entering anything into the search box breaks the complete layout.

The reason is, that the height of the `slider` and the search box diff are both reduced by the following code:

```javascript
	$('#search-input').on('input', function() {
	  currentHeight = $('#search-container').outerHeight();
	  $('.search').addClass('used').css('height', currentHeight);
	});
```

I am not sure what the intention is, but removing the code makes things nicely usable.

PS: Just starting to look into chwodown, but it seems to be something I was missing for a long time 👍

**Comment by clarklab** [comment]
To be honest, I'm not sure what that did (I think it was leftover from a different slider approach) or why I wrote it that way, haha. Good catch.

PS glad you like it! Lemme know if you've got any ideas/suggestions
